version: '3.3'

services:
  phpapache:
    #image: titangene/php-apache-mysql:v1.0
    build: ./php
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www
  mysql:
    build: ./mysql
    ports:
      - "8081:8081"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: testdb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306